name: build-test-ci

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Git ref to build'
        required: true
        default: 'develop'
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - name: "Check branch"
      run: echo "workflow_run branch is $GITHUB_REF_NAME"

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.git-ref }}

    - name: Build Code
      id: code_build
      run: echo "Code is being built..."

    - name: Test Code
      id: code_test
      run: echo "Running Unit Tests."
