name: master-test

on:
  workflow_run:
    workflows: ["build"]
    branches:
    - master
    types:
    - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: "Check branch"
      run: echo "workflow_run executing from branch \'master\', which should match GITHUB_REF_NAME value of $GITHUB_REF_NAME"
