name: master-test

on:
  workflow_run:
    workflows: ["build"]
    branches:
    - master
    types:
    - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: "Check branch"
      run: echo "workflow_run branch is $GITHUB_REF_NAME"
