name: predeploy-tests

on:
  workflow_run:
    workflows: ["build"]
    branches:
    - master
    - develop
    types:
    - completed

jobs:
  test:
    runs-on: self-hosted
    steps:

    - name: "Check branch"
      run: echo "workflow_run branch is $GITHUB_REF_NAME"
